### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by RA80533** [cnst/mdoc.su#3]
Any plans to add a certificate?

**Comment by cnst** [comment]
No; we value backwards compatibility and serving every request.

HTTPS is not backwards compatible, so, it's a non-starter.  Until such time that it'd be possible to offer opportunistic encryption, we cannot in good conscience add any certificates.

More details here:

http://lists.w3.org/Archives/Public/ietf-http-wg/2015JanMar/0106.html
